In [15]:
#import data
import pandas as pd
tweets = pd.read_csv("/content/tweets.csv")
tweets.head()

   id  label                                              tweet
0   1      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1   2      0  Finally a transparant silicon case ^^ Thanks t...
2   3      0  We love this! Would you go? #talk #makememorie...
3   4      0  I'm wired I know I'm George I was made that wa...
4   5      1  What amazing service! Apple won't even talk to...

In [16]:
#reove id
tweets.drop("id", axis=1, inplace=True)
tweets.head()

   label                                              tweet
0      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1      0  Finally a transparant silicon case ^^ Thanks t...
2      0  We love this! Would you go? #talk #makememorie...
3      0  I'm wired I know I'm George I was made that wa...
4      1  What amazing service! Apple won't even talk to...

In [17]:
#preprocess data
import re
def preprocess(text):
    text = re.sub(r"@[A-Za-z0-9_]+", "", text)   # remove mentions
    text = re.sub(r"#[A-Za-z0-9_]+", "", text)   # remove hashtags
    text = re.sub(r"http\S+|www\S+", "", text)   # remove links
    text = re.sub(r"\n", " ", text)               # remove new lines
    text = re.sub(r"[^A-Za-z\s]", "", text)
    return text

tweets["tweet"] = tweets["tweet"].apply(preprocess)

In [18]:
tweets

      label                                              tweet
0         0                                     Test
1         0  Finally a transparant silicon case  Thanks to ...
2         0                 We love this Would you go
3         0  Im wired I know Im George I was made that way ...
4         1  What amazing service Apple wont even talk to m...
...     ...                                                ...
7915      0                              Live out loud
7916      0  We would like to wish you an amazing day Make ...
7917      0  Helping my lovely  year old neighbor with her ...
7918      0  Finally got my    stay connected anytimeanywhe...
7919      0                         Apple Barcelona

[7920 rows x 2 columns]

In [19]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [20]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [21]:
##### convert words to vector  using TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(tweets['tweet'])
y = tweets['label']

In [22]:
import pandas as pd
# not nessasary
# Convert sparse matrix to a DataFrame
X_df = pd.DataFrame(
    X.toarray(),
    columns=vectorizer.get_feature_names_out()
)

# Display the first few rows
X_df.head()

,aaaahhhhhhh,aah,aalborg,aand,aapl,aaron,aarrrggghhhh,aas,aashamsakal,ab,...,zoo,zoom,zoooom,zpictwittercomgskxbmkrto,zpictwittercomhnzltjvn,zpictwittercomnlmqvrxzv,zpictwittercomsschughesb,zune,zunehd,zx
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
y.value_counts()

label
0    5894
1    2026
Name: count, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [27]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
model = nb.fit(X_train, y_train)

In [28]:
pred = model.predict(X_test)
pred

array([0, 1, 0, ..., 0, 0, 0])

In [29]:
y_test

7303    0
6146    1
1977    0
5913    0
6589    0
       ..
1232    0
3000    0
2768    0
6474    0
6835    0
Name: label, Length: 1584, dtype: int64

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, pred)
cm

array([[1144,   34],
       [ 242,  164]])

In [31]:
print(accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

0.8257575757575758
              precision    recall  f1-score   support

           0       0.83      0.97      0.89      1178
           1       0.83      0.40      0.54       406

    accuracy                           0.83      1584
   macro avg       0.83      0.69      0.72      1584
weighted avg       0.83      0.83      0.80      1584